### ISSUE TITLE
Undefined method 'match' for Hash

### ISSUE THREAD

**Issue by Gimbardo** [cyril/accept_language.rb#3]
Code:
-------------
    string = request.headers.fetch("HTTP_ACCEPT_LANGUAGE")
    locale = AcceptLanguage.parse(string).match(*I18n.available_locales)

When running the code above in my application controller I get this error: Undefined method 'match' for { :"it-it"=>1.0, :it=>0.9, :"en-us"=>0.8, :en=>0.7 }:Hash

match should be used on a string, but AcceptLanguage.parse seems like returning an hash

(I'm running the example "Rails integration example" in README)

**Comment by cyril** [comment]
According to the `{ :"it-it"=>1.0, :it=>0.9, :"en-us"=>0.8, :en=>0.7 }` hash content, the corresponding code should look like:

```ruby
string = "it-it, it;q=0.9, en-us;q=0.8, en;q=0.7"
parser = AcceptLanguage.parse(string) # => #<AcceptLanguage::Parser:0x00007ff25c86e4c0 @languages_range={"it-it"=>0.1e1, "it"=>0.9e0, "en-us"=>0.8e0, "en"=>0.7e0}>
parser.match(:it, :en) # => :it
```

Note: the hash is saved in `@languages_range` inside the `parser` instance. And then we can apply on it the `match` method.

Hoping this help.

If you think this issue is done, feel free to close it, otherwise give me please the full code so that I'll be able to reproduce the bug and fix it. Thanks!

**Comment by Gimbardo** [comment]
I can give you more code, but i basically used only what i saw in your example
------------------------------
    class ApplicationController < ActionController::Base
      before_action :authenticate_user! #authentication with devise
      before_action :set_days # variables that i use in every section of my code, so i set them up here
      self.allow_forgery_protection = false if ENV['RAILS_ENV'] == 'test' #this is for api testing

      before_action :best_locale_from_request!
    
      def best_locale_from_request!
        I18n.locale = best_locale_from_request
      end
    
      def best_locale_from_request
        return I18n.default_locale unless request.headers.key?("HTTP_ACCEPT_LANGUAGE")
    
        string = request.headers.fetch("HTTP_ACCEPT_LANGUAGE") # string => it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7
        parser = AcceptLanguage.parse(string)  # parser => {:"it-it"=>1.0, :it=>0.9, :"en-us"=>0.8, :en=>0.7}
        locale = parser.match(*I18n.available_locales) # => no method match for hash
    
        # If the server cannot serve any matching language,
        # it can theoretically send back a 406 (Not Acceptable) error code.
        # But, for a better user experience, this is rarely done and more
        # common way is to ignore the Accept-Language header in this case.
        return I18n.default_locale if locale.nil?
    
        locale
      end

      private
      def set_days
        (...)
      end
    end
----------------------
<b>As you can see, our AcceptLanguage isn't actually returning a parser, as in your reply, but an hash</b>
Im using Rails 6.1.3.2 and Ruby 2.6.6p146, I dont know if this can help anyway
I also checked using bundle list, and your gem is there

Here I try to give you a bit more using rails c
--------------------------------
    Loading development environment (Rails 6.1.3.2)
    irb(main):001:0> string = "it-it, it;q=0.9, en-us;q=0.8, en;q=0.7"
    => "it-it, it;q=0.9, en-us;q=0.8, en;q=0.7"
    irb(main):002:0> parser = AcceptLanguage.parse(string)
    => {:"it-it"=>1.0, :it=>0.9, :"en-us"=>0.8, :en=>0.7}
    irb(main):003:0> parser.match(:it, :en)
    Traceback (most recent call last):
            1: from (irb):3
    NoMethodError (undefined method `match' for {:"it-it"=>1.0, :it=>0.9, :"en-us"=>0.8, :en=>0.7}:Hash)

Hope this helps

**Comment by cyril** [comment]
Thank you for this detailed reply. Okay, I think I've got it! It seems you're using the previous version of the gem.

The README related to the previous version is available here: https://github.com/cyril/accept_language.rb/tree/v1.0.1#rails-integration-example

Here's the code that should work without troubles:

```ruby
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :best_locale_from_request!

  def best_locale_from_request!
    I18n.locale = best_locale_from_request
  end

  def best_locale_from_request
    return I18n.default_locale unless request.headers.key?("HTTP_ACCEPT_LANGUAGE")

    string = request.headers.fetch("HTTP_ACCEPT_LANGUAGE")
    locale = AcceptLanguage.intersection(string, I18n.default_locale, *I18n.available_locales)

    # If the server cannot serve any matching language,
    # it can theoretically send back a 406 (Not Acceptable) error code.
    # But, for a better user experience, this is rarely done and more
    # common way is to ignore the Accept-Language header in this case.
    return I18n.default_locale if locale.nil?

    locale
  end
end
```

**Comment by Gimbardo** [comment]
Lovely, this works.  
Thank you for your time
